trigger:
  - master
  - release
variables:
  ctest.cache_extra: ''
pr: none
jobs:
  - job: VisualStudio
    timeoutInMinutes: 0
    strategy:
      maxParallel: 2
      matrix:
        v141-64-Elastix:
          CTEST_CMAKE_GENERATOR_TOOLSET: v141,host=x64
          CTEST_CMAKE_GENERATOR_PLATFORM: x64
          CTEST_CONFIGURATION_TYPE: Release
          CTEST_CMAKE_GENERATOR: "Visual Studio 16 2019"
          imageName: 'windows-2019'
          ctest.cache_extra: |
            SimpleITK_USE_ELASTIX:BOOL=ON
        v141-32:
          CTEST_CMAKE_GENERATOR_TOOLSET: v141
          CTEST_CMAKE_GENERATOR_PLATFORM: Win32
          CTEST_CONFIGURATION_TYPE: MinSizeRel
          CTEST_CMAKE_GENERATOR: "Visual Studio 16 2019"
          imageName: 'windows-2019'

    pool:
      vmImage: $(imageName)

    steps:
      - template: templates/git-download-steps.yml
      - script: |
          echo '##vso[task.prependpath]$(Agent.BuildDirectory)\bld\ITK-prefix\bin
          echo '##vso[task.prependpath]$(Agent.BuildDirectory)\bld\SimpleITK-prefix\bin
      - script: |
          echo %CXXFLAGS%
          cmake --version
          ctest -S "$(Build.SourcesDirectory)/Testing/CI/Azure/azure.cmake" -V
        displayName: Build and test
        workingDirectory: $(Agent.BuildDirectory)
        env:
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          CTEST_BINARY_DIRECTORY: $(Agent.BuildDirectory)/bld
          CXXFLAGS: /MP
          CFLAGS: /MP
          CTEST_CACHE: |
            BUILD_DOCUMENTS:BOOL=OFF
            BUILD_EXAMPLES:BOOL=OFF
            BUILD_SHARED_LIBS:BOOL=OFF
            BUILD_TESTING:BOOL=ON
            SimpleITK_EXPLICIT_INSTANTIATION:BOOL=OFF

            WRAP_DEFAULT:BOOL=OFF
            $(ctest.cache_extra)

  - job: macOS
    timeoutInMinutes: 0
    strategy:
      maxParallel: 2
      matrix:
        XCode_13-Elastix:
          imageName: 'macos-11'
          xcodeVersion: 13.4
          ctest.cache_extra: |
            SimpleITK_USE_ELASTIX:BOOL=ON
    pool:
      vmImage: $(imageName)

    steps:
      - template: templates/git-download-steps.yml
      - task: UsePythonVersion@0
        displayName: Enable Python
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
          addToPath: true
      - script: |
          python --version
          sudo python -m pip install setuptools numpy
          sudo python -m pip install ninja scikit-ci-addons lxml
        displayName: 'Install ninja dependency'
      - bash: |
          set -x
          xcode-select -p
          sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app/Contents/Developer/
          xcode-select -p
          c++ --version
          cmake --version
          ninja --version
          ctest -S ${BUILD_SOURCESDIRECTORY}/Testing/CI/Azure/azure.cmake -V -j 2
        displayName: Build and test
        env:
          CTEST_CONFIGURATION_TYPE: MinSizeRel
          CTEST_OUTPUT_ON_FAILURE: 1
          DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
          CTEST_CACHE: |
            BUILD_DOCUMENTS:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_SHARED_LIBS:BOOL=OFF
            BUILD_TESTING:BOOL=ON
            WRAP_DEFAULT:BOOL=OFF
            WRAP_PYTHON:BOOL=ON
            WRAP_JAVA:BOOL=ON
            $(ctest.cache_extra)
        workingDirectory: $(Agent.BuildDirectory)
      - script: |
          ci_addons ctest_junit_formatter $(Build.SourcesDirectory)-build > $(Agent.BuildDirectory)/JUnitTestResults.xml
        condition: succeededOrFailed()
        displayName: 'Format CTest output in JUnit format'
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "$(Agent.BuildDirectory)/JUnitTestResults.xml"
          testRunTitle: 'CTest $(Agent.OS)'
        condition: succeededOrFailed()
        displayName: 'Publish test results'

  - job: 'LinuxGCC'
    timeoutInMinutes: 360
    pool:
      name: 'Default'
      demands:
      - Agent.OS -equals Linux
    strategy:
      maxParallel: 3
      matrix:
       ITK-master:
         env_file: '/opt/rh/devtoolset-7/enable'
         ctest.cache_extra: |
           ITK_GIT_TAG:STRING=master
           CMAKE_CXX_STANDARD:STRING=14
       devtools-7:
         env_file: '/opt/rh/devtoolset-7/enable'
       devtools-8:
         env_file: '/opt/rh/devtoolset-8/enable'
       devtools-9:
         env_file: '/opt/rh/devtoolset-9/enable'
       devtools-9-Elastix:
         env_file: '/opt/rh/devtoolset-9/enable'
         ctest.cache_extra: |
            SimpleITK_USE_ELASTIX:BOOL=ON

    workspace:
      clean: all
    steps:
        - template: templates/git-download-steps.yml
        - script: |
            [[ ! -z "$(env_file)" ]] && source $(env_file)
            cmake --version
            gcc --version
            ccache -p
            ctest -S "$(Build.SourcesDirectory)/Testing/CI/Azure/azure.cmake" -V
            ccache --show-stats
          displayName: Build and test
          env:
            CTEST_OUTPUT_ON_FAILURE: 1
            DASHBOARD_BRANCH_DIRECTORY: $(Agent.BuildDirectory)/SimpleITK-dashboard
            CTEST_CACHE: |
              BUILD_DOCUMENTS:BOOL=OFF
              BUILD_EXAMPLES:BOOL=ON
              BUILD_SHARED_LIBS:BOOL=OFF
              BUILD_TESTING:BOOL=ON
              WRAP_DEFAULT:BOOL=ON
              CMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/ccache
              CMAKE_C_COMPILER_LAUNCHER=/usr/bin/ccache
              $(ctest.cache_extra)
          workingDirectory: $(Agent.BuildDirectory)
