name: Batch Build and Test

on:
  push:
   branches: ['master', 'release']
  pull_request:
    paths: .github/workflows/BatchBuild.yml
  # Enable manual running of workflow
  workflow_dispatch:

concurrency: batch-${{ github.ref }}

jobs:
  build:
    # The CMake configure and build commands are platform-agnostic and should work a cross
    # platforms.
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        include:
          - os: windows-2022
            cmake-build-type: "Release"
            cmake-generator: "Visual Studio 17 2022"
            cmake-generator-toolset: v143,host=x64
            cmake-generator-platform: x64
            ctest-cache: |
              WRAP_CSHARP:BOOL=ON
              WRAP_JAVA:BOOL=ON

          - os: windows-2019
            cmake-build-type: "Release"
            cmake-generator: "Visual Studio 16 2019"
            cmake-generator-toolset: v141,host=x64
            cmake-generator-platform: x64
            ctest-cache: |
              SimpleITK_USE_ELASTIX:BOOL=ON
              BUILD_EXAMPLES:BOOL=OFF

          - os: ubuntu-22.04
            cmake-build-type: "Release"
            cmake-generator: "Ninja"
            ctest-cache: |
              WRAP_PYTHON:BOOL=ON

          - os: macos-12
            cmake-build-type: "Release"
            cmake-generator: "Ninja"
            xcode-version: 13.1
            ctest-cache: |
              SimpleITK_USE_ELASTIX:BOOL=ON
              WRAP_PYTHON:BOOL=ON

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.sha }}"
      - uses: actions/checkout@v3
        with:
          path: SimpleITK-dashboard
          ref: dashboard
      - name: Generate External Data Hash
        shell: bash
        run: |
          git log -n 1 "${{ github.workspace }}/Testing/Data/" | tee "${{ github.workspace }}/external-data.hashable"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ runner.temp }}/.ExternalData
          key: external-data-v1-${{ hashFiles( format( '{0}/{1}', github.workspace, 'external-data.hashable') ) }}
          enableCrossOsArchive: true
          restore-keys: |
            external-data-v1-
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ninja cmake~=3.24.0
      - name: Setup XCode
        if: contains(matrix.os,  'macos')
        shell: bash
        run: |
          xcode-select -p
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer/
          xcode-select -p
      - name: Build and Test
        shell: bash
        env:
          DASHBOARD_BRANCH_DIRECTORY: "${{ github.workspace }}/SimpleITK-dashboard"
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
          CTEST_CONFIGURATION_TYPE: ${{ matrix.cmake-build-type }}
          CTEST_CMAKE_GENERATOR: "${{ matrix.cmake-generator }}"
          CTEST_SOURCE_DIRECTORY: "${{ github.workspace }}"
          CTEST_CMAKE_GENERATOR_TOOLSET: "${{ matrix.cmake-generator-toolset }}"
          CTEST_CMAKE_GENERATOR_PLATFORM: "${{ matrix.cmake-generator-platform }}"
          CTEST_OUTPUT_ON_FAILURE: 1
          CTEST_CACHE: |
            WRAP_DEFAULT:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_TESTING:BOOL=ON
            ${{ matrix.ctest-cache }}
        run: |
          cmake --version
          ninja --version
          ctest -S ${CTEST_SOURCE_DIRECTORY}/.github/workflows/github_actions.cmake -V -j 2
