name: Nightly Build

on:
  schedule:
    # Every day at 9:11 AM UTC or 5:11 AM EST
    - cron: '11 9 * * *'
  pull_request:
    paths: .github/workflows/Nightly.yml
  workflow_dispatch:

jobs:
  matrix-jobs:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:

          - os: coverage-x64
            name: coverage
            cmake-build-type: "RelWithDebInfo"
            ctest-cache: |
              CMAKE_CXX_FLAGS:STRING=-g -O0 --coverage
              CMAKE_C_FLAGS:STRING=-g -O0 --coverage
              CMAKE_EXE_LINKER_FLAGS:STRING=-g -O0 -lgcov
            ctest-extra-args: |
              -Ddashboard_do_coverage=1 \
              -Ddashboard_track="Nightly" \
              -DCTEST_COVERAGE_COMMAND="$(which gcov)"

          - os: coverage-x64
            name: valgrind
            cmake-build-type: "RelWithDebInfo"
            ctest-test-timeout: 10000
            ctest-extra-args: |
              -Ddashboard_do_memcheck=1 \
              -Ddashboard_track="Nightly" \
              -DCTEST_MEMORYCHECK_COMMAND="$(type -p valgrind)" \
              -DCTEST_MEMORYCHECK_COMMAND_OPTIONS="--trace-children=yes --quiet --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --verbose --demangle=yes --gen-suppressions=all  --child-silent-after-fork=yes" \
              -DCTEST_MEMORYCHECK_SUPPRESSIONS_FILE="${CTEST_SOURCE_DIRECTORY}/CMake/Valgrind-Ubuntu2004.supp"

    env:
      CTEST_SOURCE_DIRECTORY: "${{ github.workspace }}"
      CTEST_BINARY_DIRECTORY: "${{ github.workspace }}/bld"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.sha }}"
      - uses: actions/checkout@v3
        with:
          path: SimpleITK-dashboard
          ref: dashboard
      - name: Generate External Data Hash
        shell: bash
        run: |
          git log -n 1 "${{ github.workspace }}/Testing/Data/" | tee "${{ github.workspace }}/external-data.hashable"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ runner.temp }}/.ExternalData
          key: external-data-v1-${{ hashFiles( format( '{0}/{1}', github.workspace, 'external-data.hashable') ) }}
          enableCrossOsArchive: true
          restore-keys: |
            external-data-v1-
      - name: Build and Test
        shell: bash
        env:
          DASHBOARD_BRANCH_DIRECTORY: "${{ github.workspace }}/SimpleITK-dashboard"
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
          CTEST_CONFIGURATION_TYPE: ${{ matrix.cmake-build-type }}
          CTEST_CMAKE_GENERATOR: "Ninja"
          CTEST_OUTPUT_ON_FAILURE: 1
          CTEST_TEST_TIMEOUT: ${{ matrix.ctest-test-timeout }}
          CTEST_CACHE: |
            WRAP_DEFAULT:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_TESTING:BOOL=ON
            ${{ matrix.ctest-cache }}

        run: |
          cmake --version
          gcov --version
          ctest -S ${CTEST_SOURCE_DIRECTORY}/.github/workflows/github_actions.cmake -V -- \
            ${{ matrix.ctest-extra-args }}
